version: '3.8'
services:
  db:
    image: postgres:15
    container_name: structurizer-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: structurizer
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # To avoid conflicts locally with llm-structurizer-db instance
    networks:
      - structurizer_network
  app:
    build:
      context: .
      target: production
    container_name: structurizer-app
    restart: always
    environment:
      NODE_ENV: production
      LLM_STRUCTURIZER_URL: http://llm-structurizer-app:3000
      DATABASE_URL: postgresql://postgres:root@structurizer-db:5432/structurizer?schema=public&connect_timeout=300
      NEXTAUTH_SECRET: #### YOUR SECRET HERE ####
      NEXTAUTH_URL: http://localhost:3001
      S3_ACCESS_KEY_ID: #### YOUR S3 CREDENTIALS HERE ####
      S3_SECRET_ACCESS_KEY: #### YOUR S3 CREDENTIALS HERE ####
      S3_BUCKET: #### YOUR S3 CREDENTIALS HERE ####
      S3_REGION: #### YOUR S3 CREDENTIALS HERE ####
      S3_ENDPOINT: #### YOUR S3 CREDENTIALS HERE ####
      X_API_KEY: #### YOUR LLM-STRUCTURIZER APPLICATION KEY HERE ####
      OPENAI_API_KEY: #### YOUR OPENAI API KEY HERE ####
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - structurizer_network
      - llm-structurizer_network # To allow communication with llm-structurizer-app
volumes:
  db_data:
    name: structurizer-data
networks:
  structurizer_network:
    name: structurizer_network
  llm-structurizer_network:
    name: llm-structurizer_network
    external: true